name: Test Python Runtime
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-macos-runtime:
    strategy:
      matrix:
        include:
          - arch: x86_64
            os: macos-15-intel

          - arch: aarch64
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare macOS runtime
        run: |
          # 下载 Python 静态运行时环境
          echo arch: $(uname -m)
          wget https://github.com/ScottSloan/Python-Static/releases/download/v0.0.9/macos_${{ matrix.arch }}_runtime.zip
        
          unzip macos_${{ matrix.arch }}_runtime.zip -d Bili23-Downloader

          chmod +x Bili23-Downloader/bili23-downloader
          chmod +x Bili23-Downloader/bundle/ffmpeg

      - name: Download source code
        run: |
          # 下载源代码
          git clone https://github.com/ScottSloan/Bili23-Downloader.git Bili23-Downloader-Source
          git -C Bili23-Downloader-Source checkout dev

          mkdir -p Bili23-Downloader/script
          cp -r Bili23-Downloader-Source/src/* Bili23-Downloader/script

      - name: Test macOS runtime
        run: |
          cd Bili23-Downloader

          # 打印系统版本
          echo "System Version:"
          echo "macOS Version: $(sw_vers -productVersion)"
          echo "Kernel Version: $(uname -r)"

          # 测试 ffmpeg
          echo ""
          echo "FFmpeg Test:"
          ./bundle/ffmpeg -version

          # 测试 loader
          echo ""
          echo "Loader Test:"
          ./bili23-downloader & APP_PID=$!

          # 5 秒后检查进程是否仍在运行
          sleep 5
          ps -p $APP_PID
          kill $APP_PID

      